M48
; DRILL file {KiCad 8.0.3} date 2024-07-10T23:14:38+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-10T23:14:38+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X9.652Y-52.024
X9.652Y-78.024
T2
X5.0Y-5.0
X5.0Y-85.0
X115.0Y-5.0
X115.0Y-85.0
M30
