M48
; DRILL file {KiCad 8.0.3} date 2024-11-10T15:02:51+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-10T15:02:51+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X132.907Y-66.18
X132.907Y-83.98
T2
X152.0Y-57.5
X178.0Y-57.5
T3
X105.0Y-55.0
X105.0Y-125.0
X185.0Y-55.0
X185.0Y-125.0
M30
