M48
; DRILL file {KiCad 8.0.3} date 2024-07-10T23:00:11+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-10T23:00:11+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X41.575Y-24.03
X46.425Y-24.03
T2
X41.275Y-21.0
X46.725Y-21.0
T3
X5.0Y-5.0
X5.0Y-85.0
X85.0Y-5.0
X85.0Y-85.0
M30
