M48
; DRILL file {KiCad 8.0.3} date 2024-07-10T23:22:50+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-10T23:22:50+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X70.75Y-41.8
X70.75Y-59.6
X70.85Y-4.9
X70.85Y-22.7
T2
X75.3Y-82.3
X101.3Y-82.3
T3
X5.0Y-5.0
X5.0Y-85.0
X115.0Y-5.0
X115.0Y-85.0
M30
